/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SimulationUI;
import antgame.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Software Engineering Group 12
 * 
 * UI supports custom works but the backend does not.
 */
public class setting_window extends javax.swing.JFrame {
    
    SetUp singlePlayer;
    private int brainCount = 0;
    private String brainPath;
    private String playerName;
    private MainMenu menu;
    private MouseListener m;
    
    /**
     * Creates new form setting_window
     */
    public setting_window(MainMenu menu) {
        this.menu = menu;
        initComponents();
        m = new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                loadBrain(e);
            }

            @Override
            public void mousePressed(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                loadBrain(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        this.jFileChooser_Single_Settings_PlayerGen_Load_LoadBrain.addMouseListener(m);
        this.jFileChooser_Single_Settings_WorldGen_LoadBWolrd.addMouseListener(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Single_Settings_Menu_Bar = new javax.swing.JPanel();
        jLabel_Single_Settings_Title = new javax.swing.JLabel();
        jButton_Sinlge_Setting_Return = new javax.swing.JButton();
        jButton_Single_Settings_Start = new javax.swing.JButton();
        jPanel_Single_Settings_WorldGen = new javax.swing.JPanel();
        jLabel_Single_Settings_WorldGen_Title = new javax.swing.JLabel();
        jPanel_Single_Settings_WorldGen_Load = new javax.swing.JPanel();
        jLabel_Single_Settings_WorldGen_LoadTitle = new javax.swing.JLabel();
        jFileChooser_Single_Settings_WorldGen_LoadBWolrd = new javax.swing.JFileChooser();
        jPanel_Single_Settings_WorldGen_Create = new javax.swing.JPanel();
        jLabel_Single_Settings_WorldGen_Create_Title = new javax.swing.JLabel();
        jPanel_Single_Settings_WorldGen_Create_Criteria = new javax.swing.JPanel();
        jLabel_Single_Settings_WorldGen_Create_CriteriaX = new javax.swing.JLabel();
        jLabel_Single_Settings_WorldGen_Create_CriteriaY = new javax.swing.JLabel();
        jLabel_Single_Settings_WorldGen_Create_CriteriaAHS = new javax.swing.JLabel();
        jLabel_Single_Settings_WorldGen_Create_CriteriaNoRocks = new javax.swing.JLabel();
        jLabel_Single_Settings_WorldGen_Create_CriteriaRockSize = new javax.swing.JLabel();
        jLabel_Single_Settings_WorldGen_Create_CriteriaNoFood = new javax.swing.JLabel();
        jLabel_Single_Settings_WorldGen_Create_CriteriaFoodSize = new javax.swing.JLabel();
        jPanel_Single_Settings_WorldGen_Create_CriteriaInput = new javax.swing.JPanel();
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputX = new javax.swing.JTextField();
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputY = new javax.swing.JTextField();
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputAHS = new javax.swing.JTextField();
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoRocks = new javax.swing.JTextField();
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputSizeRock = new javax.swing.JTextField();
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoFood = new javax.swing.JTextField();
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputFoodSize = new javax.swing.JTextField();
        jPanel_Single_Settings_PlayerGen = new javax.swing.JPanel();
        jLabel_Single_Settings_PlayerGen_Title = new javax.swing.JLabel();
        jPanel_Single_Settings_PlayerGen_Load = new javax.swing.JPanel();
        jLabel_Single_Settings_PlayerGen_Load_LoadTitle = new javax.swing.JLabel();
        jFileChooser_Single_Settings_PlayerGen_Load_LoadBrain = new javax.swing.JFileChooser();
        jLabel_Single_Settings_PlayerGen_Load_PlayerNameTitle = new javax.swing.JLabel();
        jTextField_Single_Settings_PlayerGen_Load_PlayerNameInput = new javax.swing.JTextField();
        jButton_Single_Settings_PlayerGen_Load_PlayerLoad = new javax.swing.JButton();
        jLabel_Single_Settings_PlayerGen_Note = new javax.swing.JLabel();
        jPanel_Single_Settings_PlayerGen_GameStatus = new javax.swing.JPanel();
        jLabel_Single_Settings_PlayerGen_Status_Title = new javax.swing.JLabel();
        jPanel_Single_Settings_PlayerGen_Status_Criteria = new javax.swing.JPanel();
        jLabel_Single_Settings_PlayerGen_Status_Criteria1 = new javax.swing.JLabel();
        jLabel_Single_Settings_PlayerGen_Status_Criteria2 = new javax.swing.JLabel();
        jLabel_Single_Settings_PlayerGen_Status_Criteria3 = new javax.swing.JLabel();
        jPanel_Single_Settings_PlayerGen_Status_CriteriaCheck = new javax.swing.JPanel();
        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus1 = new javax.swing.JLabel();
        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus2 = new javax.swing.JLabel();
        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus3 = new javax.swing.JLabel();
        jPanel_Single_Settings_Logo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Single_Settings_Menu_Bar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Single_Settings_Menu_Bar.setName("jpanel_menuBar"); // NOI18N

        jLabel_Single_Settings_Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_Single_Settings_Title.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_Single_Settings_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Single_Settings_Title.setText("Single Match Settings");

        jButton_Sinlge_Setting_Return.setForeground(new java.awt.Color(0, 0, 102));
        jButton_Sinlge_Setting_Return.setText("Back to main menu");
        jButton_Sinlge_Setting_Return.setMaximumSize(new java.awt.Dimension(240, 23));
        jButton_Sinlge_Setting_Return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMM(evt);
            }
        });

        jButton_Single_Settings_Start.setForeground(new java.awt.Color(0, 0, 102));
        jButton_Single_Settings_Start.setText("Start match");
        jButton_Single_Settings_Start.setToolTipText("");
        jButton_Single_Settings_Start.setActionCommand("Start Match");
        jButton_Single_Settings_Start.setMaximumSize(new java.awt.Dimension(240, 23));
        jButton_Single_Settings_Start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMatch(evt);
            }
        });

        javax.swing.GroupLayout Single_Settings_Menu_BarLayout = new javax.swing.GroupLayout(Single_Settings_Menu_Bar);
        Single_Settings_Menu_Bar.setLayout(Single_Settings_Menu_BarLayout);
        Single_Settings_Menu_BarLayout.setHorizontalGroup(
            Single_Settings_Menu_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Single_Settings_Menu_BarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Single_Settings_Menu_BarLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jButton_Sinlge_Setting_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton_Single_Settings_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Single_Settings_Menu_BarLayout.setVerticalGroup(
            Single_Settings_Menu_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Single_Settings_Menu_BarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Single_Settings_Menu_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Sinlge_Setting_Return, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton_Single_Settings_Start, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_Single_Settings_WorldGen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_WorldGen_Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Single_Settings_WorldGen_Title.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Single_Settings_WorldGen_Title.setText("World Settings");

        jPanel_Single_Settings_WorldGen_Load.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_WorldGen_LoadTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Single_Settings_WorldGen_LoadTitle.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Single_Settings_WorldGen_LoadTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Single_Settings_WorldGen_LoadTitle.setText("Load world from file");
        jLabel_Single_Settings_WorldGen_LoadTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jFileChooser_Single_Settings_WorldGen_LoadBWolrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getWorldFile(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Single_Settings_WorldGen_LoadLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_WorldGen_Load);
        jPanel_Single_Settings_WorldGen_Load.setLayout(jPanel_Single_Settings_WorldGen_LoadLayout);
        jPanel_Single_Settings_WorldGen_LoadLayout.setHorizontalGroup(
            jPanel_Single_Settings_WorldGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGen_LoadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_WorldGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Single_Settings_WorldGen_LoadLayout.createSequentialGroup()
                        .addComponent(jLabel_Single_Settings_WorldGen_LoadTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jFileChooser_Single_Settings_WorldGen_LoadBWolrd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Single_Settings_WorldGen_LoadLayout.setVerticalGroup(
            jPanel_Single_Settings_WorldGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGen_LoadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_WorldGen_LoadTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jFileChooser_Single_Settings_WorldGen_LoadBWolrd, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Single_Settings_WorldGen_Create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_WorldGen_Create_Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Single_Settings_WorldGen_Create_Title.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Single_Settings_WorldGen_Create_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Single_Settings_WorldGen_Create_Title.setText("Create new world file");
        jLabel_Single_Settings_WorldGen_Create_Title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_Single_Settings_WorldGen_Create_Criteria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_WorldGen_Create_CriteriaX.setText("Width (x size)");

        jLabel_Single_Settings_WorldGen_Create_CriteriaY.setText("Height (y size)");

        jLabel_Single_Settings_WorldGen_Create_CriteriaAHS.setText("Ant hill size");

        jLabel_Single_Settings_WorldGen_Create_CriteriaNoRocks.setText("Number of rocks");

        jLabel_Single_Settings_WorldGen_Create_CriteriaRockSize.setText("Size of rocks");

        jLabel_Single_Settings_WorldGen_Create_CriteriaNoFood.setText("Amount of food deposits");

        jLabel_Single_Settings_WorldGen_Create_CriteriaFoodSize.setText("Size of food deposits");

        javax.swing.GroupLayout jPanel_Single_Settings_WorldGen_Create_CriteriaLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_WorldGen_Create_Criteria);
        jPanel_Single_Settings_WorldGen_Create_Criteria.setLayout(jPanel_Single_Settings_WorldGen_Create_CriteriaLayout);
        jPanel_Single_Settings_WorldGen_Create_CriteriaLayout.setHorizontalGroup(
            jPanel_Single_Settings_WorldGen_Create_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGen_Create_CriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_WorldGen_Create_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaAHS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaNoRocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaRockSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaNoFood, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaFoodSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Single_Settings_WorldGen_Create_CriteriaLayout.setVerticalGroup(
            jPanel_Single_Settings_WorldGen_Create_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGen_Create_CriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaAHS, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaNoRocks, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaRockSize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaNoFood, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_WorldGen_Create_CriteriaFoodSize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel_Single_Settings_WorldGen_Create_CriteriaInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_Single_Settings_WorldGen_Create_CriteriaInputX.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputX.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputX.setText("Enter width of the world here...");

        jTextField_Single_Settings_WorldGen_Create_CriteriaInputY.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputY.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputY.setText("Eneter height of the world here...");

        jTextField_Single_Settings_WorldGen_Create_CriteriaInputAHS.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputAHS.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputAHS.setText("Enter size of the ant hills here...");

        jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoRocks.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoRocks.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoRocks.setText("Eneter number of rocks to spawn in the world here...");

        jTextField_Single_Settings_WorldGen_Create_CriteriaInputSizeRock.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputSizeRock.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputSizeRock.setText("Eneter the size of rocks in the world here...");

        jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoFood.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoFood.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoFood.setText("Enter the number of food deposits to spawn in the world here...");

        jTextField_Single_Settings_WorldGen_Create_CriteriaInputFoodSize.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputFoodSize.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Single_Settings_WorldGen_Create_CriteriaInputFoodSize.setText("Enter the size of food deposits in the world here...");

        javax.swing.GroupLayout jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_WorldGen_Create_CriteriaInput);
        jPanel_Single_Settings_WorldGen_Create_CriteriaInput.setLayout(jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout);
        jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout.setHorizontalGroup(
            jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputX)
                    .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputY, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputAHS)
                    .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoRocks)
                    .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputSizeRock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoFood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputFoodSize, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout.setVerticalGroup(
            jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGen_Create_CriteriaInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputAHS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoRocks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputSizeRock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoFood, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Single_Settings_WorldGen_Create_CriteriaInputFoodSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_Single_Settings_WorldGen_CreateLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_WorldGen_Create);
        jPanel_Single_Settings_WorldGen_Create.setLayout(jPanel_Single_Settings_WorldGen_CreateLayout);
        jPanel_Single_Settings_WorldGen_CreateLayout.setHorizontalGroup(
            jPanel_Single_Settings_WorldGen_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGen_CreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_WorldGen_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Single_Settings_WorldGen_CreateLayout.createSequentialGroup()
                        .addComponent(jLabel_Single_Settings_WorldGen_Create_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_Single_Settings_WorldGen_CreateLayout.createSequentialGroup()
                        .addComponent(jPanel_Single_Settings_WorldGen_Create_Criteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Single_Settings_WorldGen_Create_CriteriaInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_Single_Settings_WorldGen_CreateLayout.setVerticalGroup(
            jPanel_Single_Settings_WorldGen_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGen_CreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_WorldGen_Create_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Single_Settings_WorldGen_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Single_Settings_WorldGen_Create_CriteriaInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Single_Settings_WorldGen_Create_Criteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_Single_Settings_WorldGenLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_WorldGen);
        jPanel_Single_Settings_WorldGen.setLayout(jPanel_Single_Settings_WorldGenLayout);
        jPanel_Single_Settings_WorldGenLayout.setHorizontalGroup(
            jPanel_Single_Settings_WorldGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_WorldGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Single_Settings_WorldGenLayout.createSequentialGroup()
                        .addComponent(jLabel_Single_Settings_WorldGen_Title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel_Single_Settings_WorldGen_Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Single_Settings_WorldGen_Create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Single_Settings_WorldGenLayout.setVerticalGroup(
            jPanel_Single_Settings_WorldGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_WorldGenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_WorldGen_Title)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Single_Settings_WorldGen_Load, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Single_Settings_WorldGen_Create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_Single_Settings_PlayerGen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_PlayerGen_Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Single_Settings_PlayerGen_Title.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Single_Settings_PlayerGen_Title.setText("Player Settings");

        jPanel_Single_Settings_PlayerGen_Load.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_PlayerGen_Load_LoadTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Single_Settings_PlayerGen_Load_LoadTitle.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Single_Settings_PlayerGen_Load_LoadTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Single_Settings_PlayerGen_Load_LoadTitle.setText("Load brain from file");
        jLabel_Single_Settings_PlayerGen_Load_LoadTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jFileChooser_Single_Settings_PlayerGen_Load_LoadBrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadBrain(evt);
            }
        });

        jLabel_Single_Settings_PlayerGen_Load_PlayerNameTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Single_Settings_PlayerGen_Load_PlayerNameTitle.setText("Player Name");

        jTextField_Single_Settings_PlayerGen_Load_PlayerNameInput.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Single_Settings_PlayerGen_Load_PlayerNameInput.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Single_Settings_PlayerGen_Load_PlayerNameInput.setText("Enter player name here...");

        jButton_Single_Settings_PlayerGen_Load_PlayerLoad.setText("Load player");
        jButton_Single_Settings_PlayerGen_Load_PlayerLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadPlayer(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Single_Settings_PlayerGen_LoadLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_PlayerGen_Load);
        jPanel_Single_Settings_PlayerGen_Load.setLayout(jPanel_Single_Settings_PlayerGen_LoadLayout);
        jPanel_Single_Settings_PlayerGen_LoadLayout.setHorizontalGroup(
            jPanel_Single_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGen_LoadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Single_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Load_LoadTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Single_Settings_PlayerGen_LoadLayout.createSequentialGroup()
                        .addComponent(jLabel_Single_Settings_PlayerGen_Load_PlayerNameTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Single_Settings_PlayerGen_Load_PlayerNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton_Single_Settings_PlayerGen_Load_PlayerLoad))
                    .addComponent(jFileChooser_Single_Settings_PlayerGen_Load_LoadBrain, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel_Single_Settings_PlayerGen_LoadLayout.setVerticalGroup(
            jPanel_Single_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGen_LoadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_PlayerGen_Load_LoadTitle)
                .addGap(18, 18, 18)
                .addComponent(jFileChooser_Single_Settings_PlayerGen_Load_LoadBrain, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Single_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Load_PlayerNameTitle)
                    .addComponent(jTextField_Single_Settings_PlayerGen_Load_PlayerNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Single_Settings_PlayerGen_Load_PlayerLoad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Single_Settings_PlayerGen_Note.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_Single_Settings_PlayerGen_Note.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Single_Settings_PlayerGen_Note.setText("Please load brains one-by-one, in the order of players");

        jPanel_Single_Settings_PlayerGen_GameStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_PlayerGen_Status_Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Single_Settings_PlayerGen_Status_Title.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Single_Settings_PlayerGen_Status_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Single_Settings_PlayerGen_Status_Title.setText("Current Game Status");
        jLabel_Single_Settings_PlayerGen_Status_Title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_Single_Settings_PlayerGen_Status_Criteria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_PlayerGen_Status_Criteria1.setText("Valid map loaded");

        jLabel_Single_Settings_PlayerGen_Status_Criteria2.setText("Player 1 loaded");

        jLabel_Single_Settings_PlayerGen_Status_Criteria3.setText("Player 2 loaded");

        javax.swing.GroupLayout jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_PlayerGen_Status_Criteria);
        jPanel_Single_Settings_PlayerGen_Status_Criteria.setLayout(jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout);
        jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout.setHorizontalGroup(
            jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout.setVerticalGroup(
            jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGen_Status_CriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Single_Settings_PlayerGen_Status_CriteriaCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus1.setText("NO");

        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus2.setText("NO");

        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus3.setText("NO");

        javax.swing.GroupLayout jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_PlayerGen_Status_CriteriaCheck);
        jPanel_Single_Settings_PlayerGen_Status_CriteriaCheck.setLayout(jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout);
        jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout.setHorizontalGroup(
            jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout.setVerticalGroup(
            jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGen_Status_CriteriaCheckLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_Single_Settings_PlayerGen_GameStatusLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_PlayerGen_GameStatus);
        jPanel_Single_Settings_PlayerGen_GameStatus.setLayout(jPanel_Single_Settings_PlayerGen_GameStatusLayout);
        jPanel_Single_Settings_PlayerGen_GameStatusLayout.setHorizontalGroup(
            jPanel_Single_Settings_PlayerGen_GameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGen_GameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_PlayerGen_GameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jPanel_Single_Settings_PlayerGen_Status_Criteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Single_Settings_PlayerGen_Status_CriteriaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Single_Settings_PlayerGen_GameStatusLayout.setVerticalGroup(
            jPanel_Single_Settings_PlayerGen_GameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGen_GameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_PlayerGen_GameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Single_Settings_PlayerGen_Status_CriteriaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Single_Settings_PlayerGen_GameStatusLayout.createSequentialGroup()
                        .addComponent(jLabel_Single_Settings_PlayerGen_Status_Title)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Single_Settings_PlayerGen_Status_Criteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Single_Settings_Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel_Single_Settings_LogoLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_Logo);
        jPanel_Single_Settings_Logo.setLayout(jPanel_Single_Settings_LogoLayout);
        jPanel_Single_Settings_LogoLayout.setHorizontalGroup(
            jPanel_Single_Settings_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_Single_Settings_LogoLayout.setVerticalGroup(
            jPanel_Single_Settings_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_Single_Settings_PlayerGenLayout = new javax.swing.GroupLayout(jPanel_Single_Settings_PlayerGen);
        jPanel_Single_Settings_PlayerGen.setLayout(jPanel_Single_Settings_PlayerGenLayout);
        jPanel_Single_Settings_PlayerGenLayout.setHorizontalGroup(
            jPanel_Single_Settings_PlayerGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Single_Settings_PlayerGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_PlayerGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_Single_Settings_PlayerGenLayout.createSequentialGroup()
                        .addComponent(jLabel_Single_Settings_PlayerGen_Title)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Single_Settings_PlayerGen_Note, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                    .addComponent(jPanel_Single_Settings_PlayerGen_Load, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jPanel_Single_Settings_PlayerGen_GameStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Single_Settings_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel_Single_Settings_PlayerGenLayout.setVerticalGroup(
            jPanel_Single_Settings_PlayerGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Single_Settings_PlayerGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Single_Settings_PlayerGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Title)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Note))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Single_Settings_PlayerGen_Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Single_Settings_PlayerGen_GameStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Single_Settings_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Single_Settings_Menu_Bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_Single_Settings_WorldGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Single_Settings_PlayerGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Single_Settings_Menu_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Single_Settings_WorldGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Single_Settings_PlayerGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getWorldFile(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getWorldFile
        // TODO add your handling code here:  
        if (jFileChooser_Single_Settings_WorldGen_LoadBWolrd.getApproveButtonMnemonic() == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            try 
            {
                singlePlayer.loadWorld(jFileChooser_Single_Settings_WorldGen_LoadBWolrd.getSelectedFile().getAbsolutePath());
                this.jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus1.setText("YES");
                this.jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus1.setForeground(java.awt.Color.green);
            }
            catch (Exception e)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid world file");
            }
        }
        else if (jFileChooser_Single_Settings_WorldGen_LoadBWolrd.getApproveButtonMnemonic() == javax.swing.JFileChooser.CANCEL_OPTION)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "You pressed cancel");
        }
    }//GEN-LAST:event_getWorldFile

    private void loadBrain(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadBrain
        // TODO add your handling code here:
        //if (jFileChooser_Single_Settings_WorldGen_LoadBWolrd.getApproveButtonMnemonic() == javax.swing.JFileChooser.APPROVE_OPTION)
        //{
           
            brainPath = jFileChooser_Single_Settings_WorldGen_LoadBWolrd.getSelectedFile().getAbsolutePath();
              
           System.err.println("Brain path "+brainPath);
       // }
       // else if (jFileChooser_Single_Settings_WorldGen_LoadBWolrd.getApproveButtonMnemonic() == javax.swing.JFileChooser.CANCEL_OPTION)
        //{
        //    javax.swing.JOptionPane.showMessageDialog(this, "You pressed cancel");
        //}
    }//GEN-LAST:event_loadBrain

    private void loadPlayer(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadPlayer
        // TODO add your handling code here:
        try{
            singlePlayer.loadAntBrain(brainPath);
            this.brainCount += 1;
            if (brainCount == 1)
            {
                this.jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus2.setText("YES");
                this.jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus2.setForeground(java.awt.Color.green);
                }
                else if (brainCount == 2)
                {
                this.jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus3.setText("YES");
                this.jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus3.setForeground(java.awt.Color.green);
                }
                try 
                {
                    playerName = jTextField_Single_Settings_PlayerGen_Load_PlayerNameInput.getText();
                    MainMenu.validateString(playerName);
                    singlePlayer.addPlayer(playerName);
                }
                catch (Exception e)
                {
                    javax.swing.JOptionPane.showMessageDialog(this, "Player name null or too long");
                }
                
            }
            catch (Exception e)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Ant Brain");
            }
    }//GEN-LAST:event_loadPlayer

    private void backToMM(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMM
        // TODO add your handling code here:
        this.menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToMM

    private void startMatch(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMatch
        // TODO add your handling code here:
        new simulation_window(singlePlayer, menu);
        this.dispose();
    }//GEN-LAST:event_startMatch

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Single_Settings_Menu_Bar;
    private javax.swing.JButton jButton_Single_Settings_PlayerGen_Load_PlayerLoad;
    private javax.swing.JButton jButton_Single_Settings_Start;
    private javax.swing.JButton jButton_Sinlge_Setting_Return;
    private javax.swing.JFileChooser jFileChooser_Single_Settings_PlayerGen_Load_LoadBrain;
    private javax.swing.JFileChooser jFileChooser_Single_Settings_WorldGen_LoadBWolrd;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Load_LoadTitle;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Load_PlayerNameTitle;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Note;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_Criteria1;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_Criteria2;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_Criteria3;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus1;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus2;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_CriteriaStatus3;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_Title;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Title;
    private javax.swing.JLabel jLabel_Single_Settings_Title;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Create_CriteriaAHS;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Create_CriteriaFoodSize;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Create_CriteriaNoFood;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Create_CriteriaNoRocks;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Create_CriteriaRockSize;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Create_CriteriaX;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Create_CriteriaY;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Create_Title;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_LoadTitle;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Title;
    private javax.swing.JPanel jPanel_Single_Settings_Logo;
    private javax.swing.JPanel jPanel_Single_Settings_PlayerGen;
    private javax.swing.JPanel jPanel_Single_Settings_PlayerGen_GameStatus;
    private javax.swing.JPanel jPanel_Single_Settings_PlayerGen_Load;
    private javax.swing.JPanel jPanel_Single_Settings_PlayerGen_Status_Criteria;
    private javax.swing.JPanel jPanel_Single_Settings_PlayerGen_Status_CriteriaCheck;
    private javax.swing.JPanel jPanel_Single_Settings_WorldGen;
    private javax.swing.JPanel jPanel_Single_Settings_WorldGen_Create;
    private javax.swing.JPanel jPanel_Single_Settings_WorldGen_Create_Criteria;
    private javax.swing.JPanel jPanel_Single_Settings_WorldGen_Create_CriteriaInput;
    private javax.swing.JPanel jPanel_Single_Settings_WorldGen_Load;
    private javax.swing.JTextField jTextField_Single_Settings_PlayerGen_Load_PlayerNameInput;
    private javax.swing.JTextField jTextField_Single_Settings_WorldGen_Create_CriteriaInputAHS;
    private javax.swing.JTextField jTextField_Single_Settings_WorldGen_Create_CriteriaInputFoodSize;
    private javax.swing.JTextField jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoFood;
    private javax.swing.JTextField jTextField_Single_Settings_WorldGen_Create_CriteriaInputNoRocks;
    private javax.swing.JTextField jTextField_Single_Settings_WorldGen_Create_CriteriaInputSizeRock;
    private javax.swing.JTextField jTextField_Single_Settings_WorldGen_Create_CriteriaInputX;
    private javax.swing.JTextField jTextField_Single_Settings_WorldGen_Create_CriteriaInputY;
    // End of variables declaration//GEN-END:variables
}
