/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SimulationUI;

/**
 *
 * @author ns350
 */
public class setting_window_tournament extends javax.swing.JFrame {

    /**
     * Creates new form setting_window
     */
    public setting_window_tournament() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Menu_Bar = new javax.swing.JPanel();
        jLabel_Settings_Title = new javax.swing.JLabel();
        jButton_Settings_Return = new javax.swing.JButton();
        jButton_Tournament_Settings_Start = new javax.swing.JButton();
        jPanel_Settings_PlayerGen = new javax.swing.JPanel();
        jLabel_Settings_PlayerGen_Title = new javax.swing.JLabel();
        jPanel_Settings_PlayerGen_Load = new javax.swing.JPanel();
        jLabel_Settings_PlayerGen_Load_LoadTitle = new javax.swing.JLabel();
        jFileChooser_Settings_PlayerGen_Load_LoadBrain = new javax.swing.JFileChooser();
        jLabel_Settings_PlayerGen_Load_PlayerNameTitle = new javax.swing.JLabel();
        jTextField_Settings_PlayerGen_Load_PlayerNameInput = new javax.swing.JTextField();
        jButton_Settings_PlayerGen_Load_PlayerLoad = new javax.swing.JButton();
        jTextField_Settings_PlayerGen_Load_NumberPlayersInput = new javax.swing.JTextField();
        jLabel_Settings_PlayerGen_Load_NumberPlayersTitle = new javax.swing.JLabel();
        jButton_Settings_PlayerGen_Load_ConfirmPlayers = new javax.swing.JButton();
        jLabel_Settings_PlayerGen_Note = new javax.swing.JLabel();
        jPanel_Settings_PlayerGen_GameStatus = new javax.swing.JPanel();
        jLabel_Settings_PlayerGen_Status_Title = new javax.swing.JLabel();
        jPanel_Settings_PlayerGen_Status_Criteria = new javax.swing.JPanel();
        jLabel_Single_Settings_PlayerGen_Status_Criteria1 = new javax.swing.JLabel();
        jLabel_Single_Settings_PlayerGen_Status_Criteria2 = new javax.swing.JLabel();
        jPanel_Settings_PlayerGen_Status_CriteriaCheck = new javax.swing.JPanel();
        jLabel_Settings_PlayerGen_Status_CriteriaStatus1 = new javax.swing.JLabel();
        jLabel_Settings_PlayerGen_Status_CriteriaStatus2 = new javax.swing.JLabel();
        jPanel_Settings_Logo = new javax.swing.JPanel();
        jPanel_Settings_WorldGen1 = new javax.swing.JPanel();
        jLabel_Settings_WorldGen_Title1 = new javax.swing.JLabel();
        jPanel_Settings_WorldGen_Load = new javax.swing.JPanel();
        jLabel_Settings_WorldGen_LoadTitle1 = new javax.swing.JLabel();
        jFileChooser_Settings_WorldGen_LoadBWolrd1 = new javax.swing.JFileChooser();
        jPanel_Settings_WorldGen_Create = new javax.swing.JPanel();
        jLabel_Settings_WorldGen_Create_Title = new javax.swing.JLabel();
        jPanel_Settings_WorldGen_Create_Criteria = new javax.swing.JPanel();
        jLabel_Settings_WorldGen_Create_CriteriaX = new javax.swing.JLabel();
        jLabel_Settings_WorldGen_Create_CriteriaY = new javax.swing.JLabel();
        jLabel_Settings_WorldGen_Create_CriteriaAHS = new javax.swing.JLabel();
        jLabel_Settings_WorldGen_Create_CriteriaNoRocks = new javax.swing.JLabel();
        jLabel_Settings_WorldGen_Create_CriteriaRockSize = new javax.swing.JLabel();
        jLabel_Settings_WorldGen_Create_CriteriaNoFood = new javax.swing.JLabel();
        jLabel_Settings_WorldGen_Create_CriteriaFoodSize = new javax.swing.JLabel();
        jPanel_Settings_WorldGen_Create_CriteriaInput = new javax.swing.JPanel();
        jTextField_Settings_WorldGen_Create_CriteriaInputX = new javax.swing.JTextField();
        jTextField_Settings_WorldGen_Create_CriteriaInputY = new javax.swing.JTextField();
        jTextField_Settings_WorldGen_Create_CriteriaInputAHS = new javax.swing.JTextField();
        jTextField_Settings_WorldGen_Create_CriteriaInputNoRocks = new javax.swing.JTextField();
        jTextField_Settings_WorldGen_Create_CriteriaInputSizeRock = new javax.swing.JTextField();
        jTextField_Settings_WorldGen_Create_CriteriaInputNoFood = new javax.swing.JTextField();
        jTextField_Settings_WorldGen_Create_CriteriaInputFoodSize = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Main_Menu_Bar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Main_Menu_Bar.setName("jpanel_menuBar"); // NOI18N

        jLabel_Settings_Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_Settings_Title.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_Settings_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Settings_Title.setText("Tournament Settings");

        jButton_Settings_Return.setForeground(new java.awt.Color(0, 0, 102));
        jButton_Settings_Return.setText("Return to main menu");
        jButton_Settings_Return.setMaximumSize(new java.awt.Dimension(240, 23));

        jButton_Tournament_Settings_Start.setForeground(new java.awt.Color(0, 0, 102));
        jButton_Tournament_Settings_Start.setText("Start tournament");
        jButton_Tournament_Settings_Start.setMaximumSize(new java.awt.Dimension(240, 23));

        javax.swing.GroupLayout Main_Menu_BarLayout = new javax.swing.GroupLayout(Main_Menu_Bar);
        Main_Menu_Bar.setLayout(Main_Menu_BarLayout);
        Main_Menu_BarLayout.setHorizontalGroup(
            Main_Menu_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_Menu_BarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Main_Menu_BarLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jButton_Settings_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton_Tournament_Settings_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Main_Menu_BarLayout.setVerticalGroup(
            Main_Menu_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_Menu_BarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Main_Menu_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Settings_Return, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton_Tournament_Settings_Start, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_Settings_PlayerGen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_PlayerGen_Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Settings_PlayerGen_Title.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Settings_PlayerGen_Title.setText("Player Settings");

        jPanel_Settings_PlayerGen_Load.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_PlayerGen_Load_LoadTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Settings_PlayerGen_Load_LoadTitle.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Settings_PlayerGen_Load_LoadTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Settings_PlayerGen_Load_LoadTitle.setText("Load brain from file");
        jLabel_Settings_PlayerGen_Load_LoadTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_PlayerGen_Load_PlayerNameTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Settings_PlayerGen_Load_PlayerNameTitle.setText("Player Name");

        jTextField_Settings_PlayerGen_Load_PlayerNameInput.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_PlayerGen_Load_PlayerNameInput.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_PlayerGen_Load_PlayerNameInput.setText("Enter player name here...");

        jButton_Settings_PlayerGen_Load_PlayerLoad.setText("Load player");

        jTextField_Settings_PlayerGen_Load_NumberPlayersInput.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_PlayerGen_Load_NumberPlayersInput.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_PlayerGen_Load_NumberPlayersInput.setText("Enter number of players here...");

        jLabel_Settings_PlayerGen_Load_NumberPlayersTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Settings_PlayerGen_Load_NumberPlayersTitle.setText("Number of players");

        jButton_Settings_PlayerGen_Load_ConfirmPlayers.setText("Confirm number");

        javax.swing.GroupLayout jPanel_Settings_PlayerGen_LoadLayout = new javax.swing.GroupLayout(jPanel_Settings_PlayerGen_Load);
        jPanel_Settings_PlayerGen_Load.setLayout(jPanel_Settings_PlayerGen_LoadLayout);
        jPanel_Settings_PlayerGen_LoadLayout.setHorizontalGroup(
            jPanel_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGen_LoadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Settings_PlayerGen_Load_LoadTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Settings_PlayerGen_LoadLayout.createSequentialGroup()
                        .addComponent(jLabel_Settings_PlayerGen_Load_PlayerNameTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Settings_PlayerGen_Load_PlayerNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton_Settings_PlayerGen_Load_PlayerLoad))
                    .addComponent(jFileChooser_Settings_PlayerGen_Load_LoadBrain, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(jPanel_Settings_PlayerGen_LoadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_PlayerGen_Load_NumberPlayersTitle)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Settings_PlayerGen_Load_NumberPlayersInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Settings_PlayerGen_Load_ConfirmPlayers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Settings_PlayerGen_LoadLayout.setVerticalGroup(
            jPanel_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGen_LoadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_PlayerGen_Load_LoadTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Settings_PlayerGen_Load_NumberPlayersTitle)
                    .addComponent(jTextField_Settings_PlayerGen_Load_NumberPlayersInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Settings_PlayerGen_Load_ConfirmPlayers))
                .addGap(18, 18, 18)
                .addComponent(jFileChooser_Settings_PlayerGen_Load_LoadBrain, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Settings_PlayerGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Settings_PlayerGen_Load_PlayerNameTitle)
                    .addComponent(jTextField_Settings_PlayerGen_Load_PlayerNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Settings_PlayerGen_Load_PlayerLoad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Settings_PlayerGen_Note.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_Settings_PlayerGen_Note.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Settings_PlayerGen_Note.setText("Please load brains one-by-one, in the order of players");

        jPanel_Settings_PlayerGen_GameStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_PlayerGen_Status_Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Settings_PlayerGen_Status_Title.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Settings_PlayerGen_Status_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Settings_PlayerGen_Status_Title.setText("Current Game Status");
        jLabel_Settings_PlayerGen_Status_Title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_Settings_PlayerGen_Status_Criteria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Single_Settings_PlayerGen_Status_Criteria1.setText("Valid map loaded");

        jLabel_Single_Settings_PlayerGen_Status_Criteria2.setText("All players loaded");

        javax.swing.GroupLayout jPanel_Settings_PlayerGen_Status_CriteriaLayout = new javax.swing.GroupLayout(jPanel_Settings_PlayerGen_Status_Criteria);
        jPanel_Settings_PlayerGen_Status_Criteria.setLayout(jPanel_Settings_PlayerGen_Status_CriteriaLayout);
        jPanel_Settings_PlayerGen_Status_CriteriaLayout.setHorizontalGroup(
            jPanel_Settings_PlayerGen_Status_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGen_Status_CriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_PlayerGen_Status_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Settings_PlayerGen_Status_CriteriaLayout.setVerticalGroup(
            jPanel_Settings_PlayerGen_Status_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGen_Status_CriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Single_Settings_PlayerGen_Status_Criteria2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Settings_PlayerGen_Status_CriteriaCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_PlayerGen_Status_CriteriaStatus1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Settings_PlayerGen_Status_CriteriaStatus1.setText("CHANGE TEXT ACCORDING TO STATUS OF CRITERIA 1");

        jLabel_Settings_PlayerGen_Status_CriteriaStatus2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Settings_PlayerGen_Status_CriteriaStatus2.setText("CHANGE TEXT ACCORDING TO STATUS OF CRITERIA 2");

        javax.swing.GroupLayout jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout = new javax.swing.GroupLayout(jPanel_Settings_PlayerGen_Status_CriteriaCheck);
        jPanel_Settings_PlayerGen_Status_CriteriaCheck.setLayout(jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout);
        jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout.setHorizontalGroup(
            jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Settings_PlayerGen_Status_CriteriaStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jLabel_Settings_PlayerGen_Status_CriteriaStatus2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout.setVerticalGroup(
            jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGen_Status_CriteriaCheckLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_PlayerGen_Status_CriteriaStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Settings_PlayerGen_Status_CriteriaStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_Settings_PlayerGen_GameStatusLayout = new javax.swing.GroupLayout(jPanel_Settings_PlayerGen_GameStatus);
        jPanel_Settings_PlayerGen_GameStatus.setLayout(jPanel_Settings_PlayerGen_GameStatusLayout);
        jPanel_Settings_PlayerGen_GameStatusLayout.setHorizontalGroup(
            jPanel_Settings_PlayerGen_GameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGen_GameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_PlayerGen_GameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Settings_PlayerGen_GameStatusLayout.createSequentialGroup()
                        .addComponent(jPanel_Settings_PlayerGen_Status_Criteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_Settings_PlayerGen_Status_CriteriaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Settings_PlayerGen_Status_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Settings_PlayerGen_GameStatusLayout.setVerticalGroup(
            jPanel_Settings_PlayerGen_GameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGen_GameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_PlayerGen_Status_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel_Settings_PlayerGen_GameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Settings_PlayerGen_Status_Criteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Settings_PlayerGen_Status_CriteriaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_Settings_Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel_Settings_LogoLayout = new javax.swing.GroupLayout(jPanel_Settings_Logo);
        jPanel_Settings_Logo.setLayout(jPanel_Settings_LogoLayout);
        jPanel_Settings_LogoLayout.setHorizontalGroup(
            jPanel_Settings_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel_Settings_LogoLayout.setVerticalGroup(
            jPanel_Settings_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_Settings_PlayerGenLayout = new javax.swing.GroupLayout(jPanel_Settings_PlayerGen);
        jPanel_Settings_PlayerGen.setLayout(jPanel_Settings_PlayerGenLayout);
        jPanel_Settings_PlayerGenLayout.setHorizontalGroup(
            jPanel_Settings_PlayerGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Settings_PlayerGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_PlayerGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_Settings_PlayerGenLayout.createSequentialGroup()
                        .addComponent(jLabel_Settings_PlayerGen_Title)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Settings_PlayerGen_Note, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                    .addComponent(jPanel_Settings_PlayerGen_Load, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jPanel_Settings_PlayerGen_GameStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Settings_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel_Settings_PlayerGenLayout.setVerticalGroup(
            jPanel_Settings_PlayerGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_PlayerGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_PlayerGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Settings_PlayerGen_Title)
                    .addComponent(jLabel_Settings_PlayerGen_Note))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Settings_PlayerGen_Load, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Settings_PlayerGen_GameStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Settings_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_Settings_WorldGen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_WorldGen_Title1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Settings_WorldGen_Title1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Settings_WorldGen_Title1.setText("World Settings");

        jPanel_Settings_WorldGen_Load.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_WorldGen_LoadTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Settings_WorldGen_LoadTitle1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Settings_WorldGen_LoadTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Settings_WorldGen_LoadTitle1.setText("Load world from file");
        jLabel_Settings_WorldGen_LoadTitle1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel_Settings_WorldGen_LoadLayout = new javax.swing.GroupLayout(jPanel_Settings_WorldGen_Load);
        jPanel_Settings_WorldGen_Load.setLayout(jPanel_Settings_WorldGen_LoadLayout);
        jPanel_Settings_WorldGen_LoadLayout.setHorizontalGroup(
            jPanel_Settings_WorldGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen_LoadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_WorldGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Settings_WorldGen_LoadLayout.createSequentialGroup()
                        .addComponent(jLabel_Settings_WorldGen_LoadTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jFileChooser_Settings_WorldGen_LoadBWolrd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Settings_WorldGen_LoadLayout.setVerticalGroup(
            jPanel_Settings_WorldGen_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen_LoadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_WorldGen_LoadTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jFileChooser_Settings_WorldGen_LoadBWolrd1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Settings_WorldGen_Create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_WorldGen_Create_Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Settings_WorldGen_Create_Title.setForeground(new java.awt.Color(0, 51, 102));
        jLabel_Settings_WorldGen_Create_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Settings_WorldGen_Create_Title.setText("Create new world file");
        jLabel_Settings_WorldGen_Create_Title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_Settings_WorldGen_Create_Criteria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Settings_WorldGen_Create_CriteriaX.setText("Width (x size)");

        jLabel_Settings_WorldGen_Create_CriteriaY.setText("Height (y size)");

        jLabel_Settings_WorldGen_Create_CriteriaAHS.setText("Ant hill size");

        jLabel_Settings_WorldGen_Create_CriteriaNoRocks.setText("Number of rocks");

        jLabel_Settings_WorldGen_Create_CriteriaRockSize.setText("Size of rocks");

        jLabel_Settings_WorldGen_Create_CriteriaNoFood.setText("Amount of food deposits");

        jLabel_Settings_WorldGen_Create_CriteriaFoodSize.setText("Size of food deposits");

        javax.swing.GroupLayout jPanel_Settings_WorldGen_Create_CriteriaLayout = new javax.swing.GroupLayout(jPanel_Settings_WorldGen_Create_Criteria);
        jPanel_Settings_WorldGen_Create_Criteria.setLayout(jPanel_Settings_WorldGen_Create_CriteriaLayout);
        jPanel_Settings_WorldGen_Create_CriteriaLayout.setHorizontalGroup(
            jPanel_Settings_WorldGen_Create_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen_Create_CriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_WorldGen_Create_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Settings_WorldGen_Create_CriteriaX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Settings_WorldGen_Create_CriteriaY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Settings_WorldGen_Create_CriteriaAHS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Settings_WorldGen_Create_CriteriaNoRocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Settings_WorldGen_Create_CriteriaRockSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Settings_WorldGen_Create_CriteriaNoFood, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jLabel_Settings_WorldGen_Create_CriteriaFoodSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Settings_WorldGen_Create_CriteriaLayout.setVerticalGroup(
            jPanel_Settings_WorldGen_Create_CriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen_Create_CriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_WorldGen_Create_CriteriaX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Settings_WorldGen_Create_CriteriaY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Settings_WorldGen_Create_CriteriaAHS, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Settings_WorldGen_Create_CriteriaNoRocks, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Settings_WorldGen_Create_CriteriaRockSize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Settings_WorldGen_Create_CriteriaNoFood, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Settings_WorldGen_Create_CriteriaFoodSize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel_Settings_WorldGen_Create_CriteriaInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_Settings_WorldGen_Create_CriteriaInputX.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_WorldGen_Create_CriteriaInputX.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_WorldGen_Create_CriteriaInputX.setText("Enter width of the world here...");

        jTextField_Settings_WorldGen_Create_CriteriaInputY.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_WorldGen_Create_CriteriaInputY.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_WorldGen_Create_CriteriaInputY.setText("Eneter height of the world here...");

        jTextField_Settings_WorldGen_Create_CriteriaInputAHS.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_WorldGen_Create_CriteriaInputAHS.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_WorldGen_Create_CriteriaInputAHS.setText("Enter size of the ant hills here...");

        jTextField_Settings_WorldGen_Create_CriteriaInputNoRocks.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_WorldGen_Create_CriteriaInputNoRocks.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_WorldGen_Create_CriteriaInputNoRocks.setText("Eneter number of rocks to spawn in the world here...");

        jTextField_Settings_WorldGen_Create_CriteriaInputSizeRock.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_WorldGen_Create_CriteriaInputSizeRock.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_WorldGen_Create_CriteriaInputSizeRock.setText("Eneter the size of rocks in the world here...");

        jTextField_Settings_WorldGen_Create_CriteriaInputNoFood.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_WorldGen_Create_CriteriaInputNoFood.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_WorldGen_Create_CriteriaInputNoFood.setText("Enter the number of food deposits to spawn in the world here...");

        jTextField_Settings_WorldGen_Create_CriteriaInputFoodSize.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField_Settings_WorldGen_Create_CriteriaInputFoodSize.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Settings_WorldGen_Create_CriteriaInputFoodSize.setText("Enter the size of food deposits in the world here...");

        javax.swing.GroupLayout jPanel_Settings_WorldGen_Create_CriteriaInputLayout = new javax.swing.GroupLayout(jPanel_Settings_WorldGen_Create_CriteriaInput);
        jPanel_Settings_WorldGen_Create_CriteriaInput.setLayout(jPanel_Settings_WorldGen_Create_CriteriaInputLayout);
        jPanel_Settings_WorldGen_Create_CriteriaInputLayout.setHorizontalGroup(
            jPanel_Settings_WorldGen_Create_CriteriaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen_Create_CriteriaInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_WorldGen_Create_CriteriaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputX)
                    .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputY, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputAHS)
                    .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputNoRocks)
                    .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputSizeRock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputNoFood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputFoodSize, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel_Settings_WorldGen_Create_CriteriaInputLayout.setVerticalGroup(
            jPanel_Settings_WorldGen_Create_CriteriaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen_Create_CriteriaInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputAHS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputNoRocks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputSizeRock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputNoFood, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Settings_WorldGen_Create_CriteriaInputFoodSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_Settings_WorldGen_CreateLayout = new javax.swing.GroupLayout(jPanel_Settings_WorldGen_Create);
        jPanel_Settings_WorldGen_Create.setLayout(jPanel_Settings_WorldGen_CreateLayout);
        jPanel_Settings_WorldGen_CreateLayout.setHorizontalGroup(
            jPanel_Settings_WorldGen_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen_CreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_WorldGen_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Settings_WorldGen_CreateLayout.createSequentialGroup()
                        .addComponent(jLabel_Settings_WorldGen_Create_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_Settings_WorldGen_CreateLayout.createSequentialGroup()
                        .addComponent(jPanel_Settings_WorldGen_Create_Criteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Settings_WorldGen_Create_CriteriaInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_Settings_WorldGen_CreateLayout.setVerticalGroup(
            jPanel_Settings_WorldGen_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen_CreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_WorldGen_Create_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Settings_WorldGen_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Settings_WorldGen_Create_CriteriaInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Settings_WorldGen_Create_Criteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_Settings_WorldGen1Layout = new javax.swing.GroupLayout(jPanel_Settings_WorldGen1);
        jPanel_Settings_WorldGen1.setLayout(jPanel_Settings_WorldGen1Layout);
        jPanel_Settings_WorldGen1Layout.setHorizontalGroup(
            jPanel_Settings_WorldGen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Settings_WorldGen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Settings_WorldGen1Layout.createSequentialGroup()
                        .addComponent(jLabel_Settings_WorldGen_Title1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel_Settings_WorldGen_Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Settings_WorldGen_Create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Settings_WorldGen1Layout.setVerticalGroup(
            jPanel_Settings_WorldGen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Settings_WorldGen1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Settings_WorldGen_Title1)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Settings_WorldGen_Load, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Settings_WorldGen_Create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Main_Menu_Bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel_Settings_WorldGen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Settings_PlayerGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_Menu_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Settings_WorldGen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Settings_PlayerGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_Menu_Bar;
    private javax.swing.JButton jButton_Settings_PlayerGen_Load_ConfirmPlayers;
    private javax.swing.JButton jButton_Settings_PlayerGen_Load_PlayerLoad;
    private javax.swing.JButton jButton_Settings_Return;
    private javax.swing.JButton jButton_Tournament_Settings_Start;
    private javax.swing.JFileChooser jFileChooser_Settings_PlayerGen_Load_LoadBrain;
    private javax.swing.JFileChooser jFileChooser_Settings_WorldGen_LoadBWolrd1;
    private javax.swing.JFileChooser jFileChooser_Single_Settings_WorldGen_LoadBWolrd;
    private javax.swing.JLabel jLabel_Settings_PlayerGen_Load_LoadTitle;
    private javax.swing.JLabel jLabel_Settings_PlayerGen_Load_NumberPlayersTitle;
    private javax.swing.JLabel jLabel_Settings_PlayerGen_Load_PlayerNameTitle;
    private javax.swing.JLabel jLabel_Settings_PlayerGen_Note;
    private javax.swing.JLabel jLabel_Settings_PlayerGen_Status_CriteriaStatus1;
    private javax.swing.JLabel jLabel_Settings_PlayerGen_Status_CriteriaStatus2;
    private javax.swing.JLabel jLabel_Settings_PlayerGen_Status_Title;
    private javax.swing.JLabel jLabel_Settings_PlayerGen_Title;
    private javax.swing.JLabel jLabel_Settings_Title;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Create_CriteriaAHS;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Create_CriteriaFoodSize;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Create_CriteriaNoFood;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Create_CriteriaNoRocks;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Create_CriteriaRockSize;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Create_CriteriaX;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Create_CriteriaY;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Create_Title;
    private javax.swing.JLabel jLabel_Settings_WorldGen_LoadTitle1;
    private javax.swing.JLabel jLabel_Settings_WorldGen_Title1;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_Criteria1;
    private javax.swing.JLabel jLabel_Single_Settings_PlayerGen_Status_Criteria2;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_LoadTitle;
    private javax.swing.JLabel jLabel_Single_Settings_WorldGen_Title;
    private javax.swing.JPanel jPanel_Settings_Logo;
    private javax.swing.JPanel jPanel_Settings_PlayerGen;
    private javax.swing.JPanel jPanel_Settings_PlayerGen_GameStatus;
    private javax.swing.JPanel jPanel_Settings_PlayerGen_Load;
    private javax.swing.JPanel jPanel_Settings_PlayerGen_Status_Criteria;
    private javax.swing.JPanel jPanel_Settings_PlayerGen_Status_CriteriaCheck;
    private javax.swing.JPanel jPanel_Settings_WorldGen1;
    private javax.swing.JPanel jPanel_Settings_WorldGen_Create;
    private javax.swing.JPanel jPanel_Settings_WorldGen_Create_Criteria;
    private javax.swing.JPanel jPanel_Settings_WorldGen_Create_CriteriaInput;
    private javax.swing.JPanel jPanel_Settings_WorldGen_Load;
    private javax.swing.JPanel jPanel_Single_Settings_WorldGen;
    private javax.swing.JPanel jPanel_Single_Settings_WorldGen_Load;
    private javax.swing.JTextField jTextField_Settings_PlayerGen_Load_NumberPlayersInput;
    private javax.swing.JTextField jTextField_Settings_PlayerGen_Load_PlayerNameInput;
    private javax.swing.JTextField jTextField_Settings_WorldGen_Create_CriteriaInputAHS;
    private javax.swing.JTextField jTextField_Settings_WorldGen_Create_CriteriaInputFoodSize;
    private javax.swing.JTextField jTextField_Settings_WorldGen_Create_CriteriaInputNoFood;
    private javax.swing.JTextField jTextField_Settings_WorldGen_Create_CriteriaInputNoRocks;
    private javax.swing.JTextField jTextField_Settings_WorldGen_Create_CriteriaInputSizeRock;
    private javax.swing.JTextField jTextField_Settings_WorldGen_Create_CriteriaInputX;
    private javax.swing.JTextField jTextField_Settings_WorldGen_Create_CriteriaInputY;
    // End of variables declaration//GEN-END:variables
}
